services:
  - type: web
    name: mrhalal-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: yarn install --frozen-lockfile --production=false && npx prisma generate && yarn build
    startCommand: npx prisma migrate deploy && yarn start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
